/*
# CitySolver Core Schema — Auth, Complaints, Officers, Rewards, Notifications, Leaderboard

## Overview
Creates the full multi-tenant schema for the CitySolver civic complaint platform.
Three roles: citizen, officer, admin. Auth handled by Supabase Auth (auth.users).
All tables have RLS enabled with role-based policies.

## 1. New Tables
- `profiles` — extends auth.users with full_name, role, avatar, phone, ward
- `departments` — municipal departments (Roads, Sanitation, Water, etc.)
- `officers` — officer records linked to a department + auth user
- `complaints` — civic complaints filed by citizens
- `complaint_images` — additional images per complaint (one-to-many)
- `complaint_status_history` — audit trail of every status change
- `rewards` — redeemable reward catalog
- `badges` — achievement badges catalog
- `user_badges` — badges earned by users (many-to-many)
- `notifications` — in-app notifications for users

## 2. Security (RLS)
- profiles: owner read/update; admins read all; officers read citizens they serve
- departments: public read (anon + authenticated)
- officers: public read (so citizens can see officer info), admin manage
- complaints: citizens CRUD own; officers read/update assigned; admins all
- complaint_images: scoped through parent complaint ownership
- complaint_status_history: scoped through parent complaint; officers/admins insert
- rewards: public read; admins manage
- badges: public read; admins manage
- user_badges: owner read; admins manage; system inserts via trigger
- notifications: owner read/update/delete; officers/admins insert for target user

## 3. Notes
- role stored in profiles.role with CHECK constraint (citizen|officer|admin)
- complaint.id is text (e.g. "CTS-2026-0001") generated by app
- complaints.user_id defaults to auth.uid() so inserts omit it safely
- Realtime enabled on complaints, notifications, profiles for live updates
*/

-- ============ PROFILES ============
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  full_name text NOT NULL,
  role text NOT NULL DEFAULT 'citizen' CHECK (role IN ('citizen', 'officer', 'admin')),
  avatar text,
  phone text,
  ward text,
  city text DEFAULT 'New Delhi',
  state text DEFAULT 'Delhi',
  trust_score integer DEFAULT 50,
  contribution_score integer DEFAULT 0,
  coins integer DEFAULT 0,
  response_rate integer DEFAULT 0,
  monthly_contribution integer DEFAULT 0,
  lifetime_contribution integer DEFAULT 0,
  verified_complaints integer DEFAULT 0,
  false_reports integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_profile" ON profiles;
CREATE POLICY "select_own_profile" ON profiles FOR SELECT
  TO authenticated USING (auth.uid() = id);

DROP POLICY IF EXISTS "update_own_profile" ON profiles;
CREATE POLICY "update_own_profile" ON profiles FOR UPDATE
  TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "admin_select_all_profiles" ON profiles;
CREATE POLICY "admin_select_all_profiles" ON profiles FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

DROP POLICY IF EXISTS "admin_update_all_profiles" ON profiles;
CREATE POLICY "admin_update_all_profiles" ON profiles FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- ============ DEPARTMENTS ============
CREATE TABLE IF NOT EXISTS departments (
  id text PRIMARY KEY,
  name text NOT NULL,
  description text,
  head_officer_id uuid REFERENCES profiles(id),
  created_at timestamptz DEFAULT now()
);

ALTER TABLE departments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_departments" ON departments;
CREATE POLICY "public_read_departments" ON departments FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "admin_manage_departments" ON departments;
CREATE POLICY "admin_manage_departments" ON departments FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

DROP POLICY IF EXISTS "admin_update_departments" ON departments;
CREATE POLICY "admin_update_departments" ON departments FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- ============ OFFICERS ============
CREATE TABLE IF NOT EXISTS officers (
  id text PRIMARY KEY,
  user_id uuid REFERENCES profiles(id) ON DELETE CASCADE,
  name text NOT NULL,
  department text NOT NULL,
  rank text NOT NULL,
  avatar text,
  availability text NOT NULL DEFAULT 'available' CHECK (availability IN ('available', 'busy', 'offline')),
  workload_pct integer DEFAULT 0,
  efficiency_pct integer DEFAULT 0,
  capacity_pct integer DEFAULT 0,
  avg_resolution_hours integer DEFAULT 0,
  avg_resolution_time text DEFAULT '0h',
  assigned_count integer DEFAULT 0,
  resolved_count integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE officers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_officers" ON officers;
CREATE POLICY "public_read_officers" ON officers FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "admin_insert_officers" ON officers;
CREATE POLICY "admin_insert_officers" ON officers FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

DROP POLICY IF EXISTS "admin_update_officers" ON officers;
CREATE POLICY "admin_update_officers" ON officers FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

DROP POLICY IF EXISTS "admin_delete_officers" ON officers;
CREATE POLICY "admin_delete_officers" ON officers FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- ============ COMPLAINTS ============
CREATE TABLE IF NOT EXISTS complaints (
  id text PRIMARY KEY,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  category text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  priority text NOT NULL DEFAULT 'Medium' CHECK (priority IN ('Critical', 'High', 'Medium', 'Low')),
  status text NOT NULL DEFAULT 'Submitted' CHECK (status IN ('Submitted', 'Under Review', 'Approved', 'Assigned', 'In Progress', 'Resolved', 'Rejected')),
  location text NOT NULL,
  lat double precision NOT NULL,
  lng double precision NOT NULL,
  image_url text,
  severity integer DEFAULT 50,
  coins integer DEFAULT 0,
  officer_id text REFERENCES officers(id),
  admin_notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_complaints" ON complaints;
CREATE POLICY "select_own_complaints" ON complaints FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_complaints" ON complaints;
CREATE POLICY "insert_own_complaints" ON complaints FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_complaints" ON complaints;
CREATE POLICY "update_own_complaints" ON complaints FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_complaints" ON complaints;
CREATE POLICY "delete_own_complaints" ON complaints FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "officer_select_assigned_complaints" ON complaints;
CREATE POLICY "officer_select_assigned_complaints" ON complaints FOR SELECT
  TO authenticated USING (
    officer_id IS NOT NULL AND officer_id IN (
      SELECT o.id FROM officers o WHERE o.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "officer_update_assigned_complaints" ON complaints;
CREATE POLICY "officer_update_assigned_complaints" ON complaints FOR UPDATE
  TO authenticated USING (
    officer_id IS NOT NULL AND officer_id IN (
      SELECT o.id FROM officers o WHERE o.user_id = auth.uid()
    )
  ) WITH CHECK (
    officer_id IS NOT NULL AND officer_id IN (
      SELECT o.id FROM officers o WHERE o.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "admin_select_all_complaints" ON complaints;
CREATE POLICY "admin_select_all_complaints" ON complaints FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

DROP POLICY IF EXISTS "admin_insert_complaints" ON complaints;
CREATE POLICY "admin_insert_complaints" ON complaints FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

DROP POLICY IF EXISTS "admin_update_all_complaints" ON complaints;
CREATE POLICY "admin_update_all_complaints" ON complaints FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

DROP POLICY IF EXISTS "admin_delete_all_complaints" ON complaints;
CREATE POLICY "admin_delete_all_complaints" ON complaints FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- ============ COMPLAINT IMAGES ============
CREATE TABLE IF NOT EXISTS complaint_images (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  complaint_id text NOT NULL REFERENCES complaints(id) ON DELETE CASCADE,
  image_url text NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE complaint_images ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_complaint_images" ON complaint_images;
CREATE POLICY "select_complaint_images" ON complaint_images FOR SELECT
  TO authenticated USING (
    EXISTS (
      SELECT 1 FROM complaints c
      WHERE c.id = complaint_id AND (
        c.user_id = auth.uid()
        OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
        OR c.officer_id IN (SELECT o.id FROM officers o WHERE o.user_id = auth.uid())
      )
    )
  );

DROP POLICY IF EXISTS "insert_complaint_images" ON complaint_images;
CREATE POLICY "insert_complaint_images" ON complaint_images FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (
      SELECT 1 FROM complaints c
      WHERE c.id = complaint_id AND (
        c.user_id = auth.uid()
        OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
      )
    )
  );

DROP POLICY IF EXISTS "delete_complaint_images" ON complaint_images;
CREATE POLICY "delete_complaint_images" ON complaint_images FOR DELETE
  TO authenticated USING (
    EXISTS (
      SELECT 1 FROM complaints c
      WHERE c.id = complaint_id AND (
        c.user_id = auth.uid()
        OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
      )
    )
  );

-- ============ COMPLAINT STATUS HISTORY ============
CREATE TABLE IF NOT EXISTS complaint_status_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  complaint_id text NOT NULL REFERENCES complaints(id) ON DELETE CASCADE,
  status text NOT NULL,
  changed_by uuid REFERENCES profiles(id),
  note text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE complaint_status_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_status_history" ON complaint_status_history;
CREATE POLICY "select_status_history" ON complaint_status_history FOR SELECT
  TO authenticated USING (
    EXISTS (
      SELECT 1 FROM complaints c
      WHERE c.id = complaint_id AND (
        c.user_id = auth.uid()
        OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
        OR c.officer_id IN (SELECT o.id FROM officers o WHERE o.user_id = auth.uid())
      )
    )
  );

DROP POLICY IF EXISTS "insert_status_history" ON complaint_status_history;
CREATE POLICY "insert_status_history" ON complaint_status_history FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (
      SELECT 1 FROM complaints c
      WHERE c.id = complaint_id AND (
        c.user_id = auth.uid()
        OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('admin', 'officer'))
        OR c.officer_id IN (SELECT o.id FROM officers o WHERE o.user_id = auth.uid())
      )
    )
  );

-- ============ REWARDS ============
CREATE TABLE IF NOT EXISTS rewards (
  id text PRIMARY KEY,
  name text NOT NULL,
  description text,
  cost integer NOT NULL,
  category text NOT NULL DEFAULT 'general',
  image_url text,
  unlocked boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE rewards ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_rewards" ON rewards;
CREATE POLICY "public_read_rewards" ON rewards FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "admin_insert_rewards" ON rewards;
CREATE POLICY "admin_insert_rewards" ON rewards FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

DROP POLICY IF EXISTS "admin_update_rewards" ON rewards;
CREATE POLICY "admin_update_rewards" ON rewards FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

DROP POLICY IF EXISTS "admin_delete_rewards" ON rewards;
CREATE POLICY "admin_delete_rewards" ON rewards FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- ============ BADGES ============
CREATE TABLE IF NOT EXISTS badges (
  id text PRIMARY KEY,
  name text NOT NULL,
  description text,
  tier text NOT NULL DEFAULT 'bronze' CHECK (tier IN ('bronze', 'silver', 'gold', 'platinum')),
  icon text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE badges ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_badges" ON badges;
CREATE POLICY "public_read_badges" ON badges FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "admin_manage_badges" ON badges;
CREATE POLICY "admin_manage_badges" ON badges FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

DROP POLICY IF EXISTS "admin_update_badges" ON badges;
CREATE POLICY "admin_update_badges" ON badges FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- ============ USER BADGES ============
CREATE TABLE IF NOT EXISTS user_badges (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  badge_id text NOT NULL REFERENCES badges(id) ON DELETE CASCADE,
  earned_at timestamptz DEFAULT now(),
  UNIQUE (user_id, badge_id)
);

ALTER TABLE user_badges ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_user_badges" ON user_badges;
CREATE POLICY "select_own_user_badges" ON user_badges FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "admin_select_all_user_badges" ON user_badges;
CREATE POLICY "admin_select_all_user_badges" ON user_badges FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

DROP POLICY IF EXISTS "admin_insert_user_badges" ON user_badges;
CREATE POLICY "admin_insert_user_badges" ON user_badges FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

DROP POLICY IF EXISTS "admin_delete_user_badges" ON user_badges;
CREATE POLICY "admin_delete_user_badges" ON user_badges FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- ============ NOTIFICATIONS ============
CREATE TABLE IF NOT EXISTS notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  type text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  complaint_id text,
  read boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_notifications" ON notifications;
CREATE POLICY "select_own_notifications" ON notifications FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_notifications" ON notifications;
CREATE POLICY "update_own_notifications" ON notifications FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_notifications" ON notifications;
CREATE POLICY "delete_own_notifications" ON notifications FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "admin_insert_notifications" ON notifications;
CREATE POLICY "admin_insert_notifications" ON notifications FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('admin', 'officer'))
  );

DROP POLICY IF EXISTS "admin_delete_notifications" ON notifications;
CREATE POLICY "admin_delete_notifications" ON notifications FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- ============ INDEXES ============
CREATE INDEX IF NOT EXISTS idx_complaints_user_id ON complaints(user_id);
CREATE INDEX IF NOT EXISTS idx_complaints_status ON complaints(status);
CREATE INDEX IF NOT EXISTS idx_complaints_officer_id ON complaints(officer_id);
CREATE INDEX IF NOT EXISTS idx_complaints_category ON complaints(category);
CREATE INDEX IF NOT EXISTS idx_complaints_created_at ON complaints(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_read ON notifications(user_id, read);
CREATE INDEX IF NOT EXISTS idx_status_history_complaint_id ON complaint_status_history(complaint_id);
CREATE INDEX IF NOT EXISTS idx_complaint_images_complaint_id ON complaint_images(complaint_id);
CREATE INDEX IF NOT EXISTS idx_officers_department ON officers(department);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON profiles(role);

-- ============ REALTIME ============
ALTER TABLE complaints REPLICA IDENTITY FULL;
ALTER TABLE notifications REPLICA IDENTITY FULL;
ALTER TABLE profiles REPLICA IDENTITY FULL;
ALTER TABLE officers REPLICA IDENTITY FULL;

-- ============ TRIGGER: updated_at ============
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS profiles_updated_at ON profiles;
CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS complaints_updated_at ON complaints;
CREATE TRIGGER complaints_updated_at BEFORE UPDATE ON complaints
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============ TRIGGER: auto-create profile on signup ============
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO profiles (id, email, full_name, role, avatar)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    COALESCE(NEW.raw_user_meta_data->>'role', 'citizen')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();
